version: 2

references:

  container_config: &container_config
    working_directory: ~/project/serverless-plugin-healthcheck
    docker:
      - image: circleci/node:6.10.3

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

jobs:
  install:
    <<: *container_config
    steps:
      - checkout
      - *restore_node_modules

      - run:
          name: Install dependencies
          command: npm install

      - *cache_node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - serverless-plugin-healthcheck

  release:
    <<: *container_config
    steps:
      - *attach_workspace

      - run:
          name: Prune devDependencies
          command: npm prune --production

      - deploy:
          command: |
            npm install -g npm-cli-login
            NPM_USER=$NPM_USER NPM_PASS=$NPM_PASSWORD NPM_EMAIL=$NPM_EMAIL npm-cli-login
            npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - release:
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/

experimental:
  notify:
    branches:
      only:
        - master
